=== SoniaKargutkar/SQLNoSQL/XMLSchema/myfamily.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- file name: myfamily.xsd -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="persons">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="person" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="fullname" type="xsd:string"/>
							<xsd:element name="childname" type="xsd:string" minOccurs="0" maxOccurs="5"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== SoniaKargutkar/SQLNoSQL/Notes/XMLSchema/myfamily.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- file name myfamily.xml -->
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="myfamily.xsd">
	<person>
		<fullname>Hege Refsnes</fullname>
		<childname>Cecilie</childname>
	</person>
	<person>
		<fullname>Tove Refsnes</fullname>
		<childname>Hege</childname>
		<childname>stale</childname>
		<childname>Jim</childname>
		<childname>Borge</childname>
	</person>
	<person>
		<fullname>Stale Refsnes</fullname>
	</person>
</persons>
