=== SoniaKargutkar/SQLNoSQL/Notes/XMLSchema/po1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- file name: po1.xsd -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:po="http://www.example.com/PO1" targetNamespace="http://www.example.com/PO1" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xsd:element name="purchaseOrder" type="po:PurchaseOrderType"/>
	<xsd:element name="comment" type="xsd:string"/>
	<xsd:complexType name="PurchaseOrderType">
		<xsd:sequence>
			<xsd:element name="shipTo" type="po:USAddress"/>
			<xsd:element name="billTo" type="po:USAddress"/>
			<!-- etc. -->
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="USAddress">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="street" type="xsd:string"/>
			<!-- etc. -->
		</xsd:sequence>
	</xsd:complexType>
	<!-- etc. -->
</xsd:schema>

=== SoniaKargutkar/SQLNoSQL/Notes/XMLSchema/po1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- file name po1.xml -->
<apo:purchaseOrder xmlns:apo="E:\Ding@IFI\Education\Course\SW_AI\XML-Schema\po1.xsd" orderDate="1999-10-20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/PO1 E:\Ding@IFI\Education\Course\SW_AI\XML-Schema\po1.xsd">
	<shipTo country="US">
		<name>Alice Smith</name>
		<street>123 Maple Street</street>
		<!-- etc. -->
	</shipTo>
	<billTo country="US">
		<name>Robert Smith</name>
		<street>8 Oak Avenue</street>
		<!-- etc. -->
	</billTo>
	<apo:comment>Hurry, my lawn is going wild</apo:comment>
	<!-- etc. -->
</apo:purchaseOrder>
